<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UniversityManagement.Core\UniversityManagement.Core.csproj" />
    <ProjectReference Include="..\UniversityManagement.Data\UniversityManagement.Data.csproj" />
    <ProjectReference Include="..\UniversityManagement.Patterns\UniversityManagement.Patterns.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
